# --- LỆNH KHỞI ĐỘNG HỆ THỐNG (JAKOOLIT) ---

# Khởi động thợ sơn hình nền (Bắt buộc)
exec-once = swww-daemon --format xrgb

# Nạp tấm hình nền gần nhất
exec-once = swww img ~/.config/hypr/wallpaper_effects/.wallpaper_current

# Khởi động thanh Taskbar ở trên
#exec-once = waybar &

# Khởi động các app hệ thống khác (Wifi, Bluetooth)
exec-once = nm-applet --indicator &
exec-once = blueman-applet &

# Khởi động trình quản lý thông báo
exec-once = dunst &
