# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(242224)
$foreground = rgb(E2E4E7)
$color0 = rgb(4A484A)
$color1 = rgb(251E26)
$color2 = rgb(504E56)
$color3 = rgb(5C5362)
$color4 = rgb(896865)
$color5 = rgb(75777F)
$color6 = rgb(81858C)
$color7 = rgb(CDD0D5)
$color8 = rgb(909195)
$color9 = rgb(312833)
$color10 = rgb(6A6872)
$color11 = rgb(7B6F83)
$color12 = rgb(B78A87)
$color13 = rgb(9C9FA9)
$color14 = rgb(ACB1BB)
$color15 = rgb(CDD0D5)
